version: "3"
services:
  db:
    image: mariadb:10.4
    container_name: "${APP_NAME}-db"
    volumes:
      - ./data:/var/lib/mysql
#      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_DATABASE_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE_NAME}"
      MYSQL_USER: "${DB_DATABASE_USER}"
      MYSQL_PASSWORD: "${DB_DATABASE_PASSWORD}"
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: ${APP_NAME}-phpmyadmin
    links:
      - db
    ports:
      - 3000:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
    env_file:
      - ./.env
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=${DB_DATABASE_USER}
      - PMA_PASSWORD=${DB_DATABASE_PASSWORD}
  app:
    build: ./php
    container_name: "${APP_NAME}-app"
    volumes:
      - ./laravel:/var/www/html
      - ./php/vhost.conf:/etc/apache2/conf-enabled/vhost.conf
    ports:
      - "8080:80"
